# -*- coding: utf-8 -*-
"""train_ia_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKhBeEgcmDeSJu4zqtFABOT1AT-amA1j
"""

import kagglehub
import os
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
import joblib

# ----------------------------------------------------
# 📌 SOLUCIÓN NLTK PARA COLAB (DESCARGA DE RECURSOS)
# ----------------------------------------------------
print("Descargando recursos de NLTK...")
try:
    # Estos comandos descargan los datos necesarios para la tokenización y stopwords
    nltk.download('punkt', quiet=True)
    nltk.download('stopwords', quiet=True)
    print("✅ Recursos de NLTK listos para usar.")
except Exception as e:
    print(f"❌ Error al descargar recursos de NLTK: {e}. La tokenización podría fallar.")
# ----------------------------------------------------


# ----------------------------------------------------
# 1. DESCARGA Y CARGA DE DATOS
# ----------------------------------------------------

print("\nDescargando el dataset de Kaggle Hub...")
path = kagglehub.dataset_download("shijo96john/animal-disease-prediction")
ruta_directorio = str(path)
nombre_archivo_csv = "cleaned_animal_disease_prediction.csv"
ruta_completa_csv = os.path.join(ruta_directorio, nombre_archivo_csv)

try:
    df = pd.read_csv(ruta_completa_csv)
    print("\n✅ DataFrame cargado exitosamente.")
except Exception as e:
    print(f"\n❌ Ocurrió un error al cargar el CSV: {e}")
    raise

# ----------------------------------------------------
# 2. COMBINACIÓN Y LIMPIEZA DE SÍNTOMAS
# ----------------------------------------------------

# Lista de columnas de síntomas para combinar
symptom_columns = [
    'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
    'Appetite_Loss', 'Vomiting', 'Diarrhea', 'Coughing',
    'Labored_Breathing', 'Lameness', 'Skin_Lesions', 'Nasal_Discharge',
    'Eye_Discharge'
]

def combine_symptoms(row):
    """Combina todas las columnas de síntomas en una única cadena de texto."""
    combined = []
    # 1. Añadir los síntomas descriptivos
    for col in ['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4']:
        if row[col] not in ['No', 'None', 'Normal']:
            combined.append(row[col])
    # 2. Añadir los síntomas binarios (si el valor es 'Yes')
    for col in symptom_columns[4:]:
        if row[col] == 'Yes':
            combined.append(col.replace('_', ' '))
    return " ".join(combined)

df['Symptoms_Combined'] = df.apply(combine_symptoms, axis=1)

# Se asume inglés para el dataset
stop_words = set(stopwords.words('english'))

def limpiar_texto(texto):
    """Aplica la limpieza de texto (minúsculas, eliminar puntuación, stopwords)."""
    if not isinstance(texto, str):
        return ""
    texto = texto.lower()
    texto = re.sub(r'[^a-z\s]', '', texto)
    tokens = word_tokenize(texto)
    tokens_limpios = [w for w in tokens if w not in stop_words and len(w) > 2]
    return " ".join(tokens_limpios)

# Aplicar la limpieza a la nueva columna combinada
df['Symptoms_clean'] = df['Symptoms_Combined'].apply(limpiar_texto)


# ----------------------------------------------------
# 3. ENTRENAMIENTO Y GUARDADO DEL MODELO
# ----------------------------------------------------

# 1. Definir X y Y (usando el nombre de columna CORRECTO)
X = df['Symptoms_clean']        # Columna de entrada limpia
Y = df['Disease_Prediction']    # Columna de salida (etiquetas)

# -------------------------------------------------------------------
# 📌 CORRECCIÓN: MANEJO DE CLASES CON UNA SOLA INSTANCIA (SOLUCIÓN AL ValueError)
# -------------------------------------------------------------------
print("\nVerificando clases con baja frecuencia para estratificación...")
clases_counts = Y.value_counts()
clases_a_eliminar = clases_counts[clases_counts < 2].index

if len(clases_a_eliminar) > 0:
    print(f"⚠️ Eliminando {len(clases_a_eliminar)} clases con una sola muestra: {list(clases_a_eliminar)}")

    # Crear un nuevo DataFrame sin las filas de clases con una sola muestra
    df_filtrado = df[~df['Disease_Prediction'].isin(clases_a_eliminar)]

    # Reasignar X y Y con los datos limpios
    X_limpio = df_filtrado['Symptoms_clean']
    Y_limpio = df_filtrado['Disease_Prediction']
    print(f"Tamaño original: {len(df)}. Tamaño después de filtrar: {len(df_filtrado)}.")
else:
    X_limpio = X
    Y_limpio = Y
    print("✅ No se encontraron clases con una sola muestra. Datos listos.")
# -------------------------------------------------------------------


# 2. Separar datos (20% para prueba)
# Usamos las variables X_limpio y Y_limpio con stratify=Y_limpio
X_train, X_test, y_train, y_test = train_test_split(
    X_limpio,
    Y_limpio,
    test_size=0.3,
    random_state=42,
    stratify=Y_limpio
)

# 3. Crear el Pipeline (Vectorizador + Clasificador)
modelo_ia = make_pipeline(
    TfidfVectorizer(),
    MultinomialNB()
)

# 4. Entrenar
print("\nIniciando el entrenamiento del modelo...")
modelo_ia.fit(X_train, y_train)
print("✅ Entrenamiento completado.")

# 5. Evaluar
predicciones = modelo_ia.predict(X_test)
print("\nReporte de Clasificación (Precisión, Recall, F1-Score):")
print(classification_report(y_test, predicciones, zero_division=0))

# 6. Guardar el modelo entrenado
# En Colab, esto lo guarda en la carpeta /content/
joblib.dump(modelo_ia, 'modelo_asistente_mascotas.pkl')
print("\nModelo guardado como 'modelo_asistente_mascotas.pkl'.")